# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/currencies', type: :request do
  # Currency. As you add validations to Currency, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Currency.create! valid_attributes
      get currencies_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      currency = Currency.create! valid_attributes
      get currency_url(currency)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_currency_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      currency = Currency.create! valid_attributes
      get edit_currency_url(currency)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Currency' do
        expect do
          post currencies_url, params: { currency: valid_attributes }
        end.to change(Currency, :count).by(1)
      end

      it 'redirects to the created currency' do
        post currencies_url, params: { currency: valid_attributes }
        expect(response).to redirect_to(currency_url(Currency.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Currency' do
        expect do
          post currencies_url, params: { currency: invalid_attributes }
        end.to change(Currency, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post currencies_url, params: { currency: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested currency' do
        currency = Currency.create! valid_attributes
        patch currency_url(currency), params: { currency: new_attributes }
        currency.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the currency' do
        currency = Currency.create! valid_attributes
        patch currency_url(currency), params: { currency: new_attributes }
        currency.reload
        expect(response).to redirect_to(currency_url(currency))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        currency = Currency.create! valid_attributes
        patch currency_url(currency), params: { currency: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested currency' do
      currency = Currency.create! valid_attributes
      expect do
        delete currency_url(currency)
      end.to change(Currency, :count).by(-1)
    end

    it 'redirects to the currencies list' do
      currency = Currency.create! valid_attributes
      delete currency_url(currency)
      expect(response).to redirect_to(currencies_url)
    end
  end
end
